name: 'gzip-size action'
description: 'Get compressed size differences for every PR'
author: 'Jason Miller'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  show-total:
    description: 'Show total size and difference.'
    default: 'true'
  collapse-unchanged:
    description: 'Move unchanged files into a separate collapsed table'
    default: 'true'
  omit-unchanged:
    description: 'Exclude unchanged files from the sizes table entirely'
runs:
  using: 'node12'
  main: 'index.js'